version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: imakita-industries
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    env_file:
      - .env
    restart: unless-stopped
    volumes:
      # 開発時にソースコードの変更を反映させたい場合はコメントアウトを外す
      # - ./src:/app/src
      # - ./public:/app/public

      # 音声ファイル用の一時ディレクトリ
      - /tmp:/tmp
